# Generated by Django 5.2.4 on 2025-08-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PKCECache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255, unique=True)),
                ('code_verifier', models.TextField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='core_pkceca_created_a8301b_idx'), models.Index(fields=['state'], name='core_pkceca_state_42170b_idx')],
            },
        ),
    ]
