# Generated by Django 5.2.4 on 2025-07-30 14:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_license_number',
            field=models.CharField(blank=True, help_text='Business license number (required for agricultural businesses)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fayda_verification_data',
            field=models.JSONField(blank=True, help_text='Stored Fayda verification data (name, DOB, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('verified', 'Verified'), ('pending', 'Pending Verification'), ('failed', 'Verification Failed')], default='not_verified', help_text='User verification status with Fayda', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user was verified', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography or description', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_license',
            field=models.CharField(blank=True, help_text='Business license number (for merchants) - deprecated, use business_license_number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size of the farm in decimal format (required for farmers)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='farm_size_unit',
            field=models.CharField(blank=True, help_text='Unit of farm size (e.g., hectares, acres)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kebele',
            field=models.CharField(blank=True, help_text='Kebele (sub-district) name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture image file (JPG, JPEG, PNG only)', null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='woreda',
            field=models.CharField(blank=True, help_text='Woreda (district) name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='User email address (used as login username)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fayda_id',
            field=models.CharField(blank=True, help_text='Fayda national ID number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='User phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, help_text='User region or location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer/Merchant'), ('agricultural_business', 'Agricultural Business'), ('admin', 'Admin')], default='farmer', help_text='Type of user account', max_length=25),
        ),
    ]
