# Generated by Django 5.2.4 on 2025-08-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_business_license_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PKCESession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='State parameter for CSRF protection', max_length=128, unique=True)),
                ('code_verifier', models.CharField(help_text='PKCE code verifier', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this session expires')),
                ('user', models.ForeignKey(help_text='User associated with this PKCE session', on_delete=django.db.models.deletion.CASCADE, related_name='pkce_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_pkce_session',
                'indexes': [models.Index(fields=['state'], name='users_pkce__state_13177c_idx'), models.Index(fields=['user', 'created_at'], name='users_pkce__user_id_4d19c1_idx')],
            },
        ),
    ]
