# Generated by Django 5.2.4 on 2025-08-02 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pkcesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area_of_expertise',
            field=models.CharField(blank=True, help_text='Area of expertise (required for experts)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate_of_expertise',
            field=models.FileField(blank=True, help_text='Certificate of expertise (PDF, JPG, JPEG, PNG only)', null=True, upload_to='expert_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='coverage_areas',
            field=models.JSONField(blank=True, help_text='List of coverage areas for logistics services', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deliveries_count',
            field=models.IntegerField(default=0, help_text='Total number of deliveries completed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.00 to 5.00)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_license_number',
            field=models.CharField(blank=True, help_text='Business license number (required for logistics providers)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer/Merchant'), ('expert', 'Expert'), ('logistics', 'Logistics'), ('admin', 'Admin')], default='farmer', help_text='Type of user account', max_length=25),
        ),
    ]
