# Generated by Django 5.2.4 on 2025-08-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_area_of_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer/Merchant'), ('expert', 'Expert'), ('logistics', 'Logistics Company'), ('admin', 'Admin')], default='farmer', help_text='Type of user account', max_length=25),
        ),
    ]
