# Generated by Django 5.2.4 on 2025-07-29 20:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('woreda', models.CharField(blank=True, max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=10)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('uv_index', models.IntegerField(null=True)),
                ('visibility', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=100)),
                ('forecast_data', models.JSONField(blank=True, default=dict)),
                ('advisory_text', models.TextField(blank=True)),
                ('data_source', models.CharField(default='Ethiopian Meteorological Agency', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', 'region'],
                'unique_together': {('region', 'woreda', 'created_at')},
            },
        ),
    ]
