# Generated by Django 5.2.4 on 2025-07-30 05:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escrow Account',
                'verbose_name_plural': 'Escrow Accounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('mobile', 'Mobile Money'), ('bank', 'Bank Account'), ('digital', 'Digital Wallet'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('provider', models.CharField(choices=[('m_pesa', 'M-Pesa'), ('telebirr', 'Telebirr'), ('hellocash', 'HelloCash'), ('cbe_birr', 'CBE Birr'), ('commercial_bank', 'Commercial Bank of Ethiopia'), ('awash_bank', 'Awash Bank'), ('dashen_bank', 'Dashen Bank'), ('bank_of_abyssinia', 'Bank of Abyssinia'), ('chapa', 'Chapa'), ('amole', 'Amole'), ('other', 'Other')], max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('verification_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_id', models.CharField(max_length=100)),
                ('total_transactions', models.IntegerField(default=0)),
                ('completed_transactions', models.IntegerField(default=0)),
                ('failed_transactions', models.IntegerField(default=0)),
                ('pending_transactions', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mobile_payments', models.IntegerField(default=0)),
                ('bank_transfers', models.IntegerField(default=0)),
                ('digital_wallet_payments', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Payment Analytics',
                'verbose_name_plural': 'Payment Analytics',
                'ordering': ['-date'],
                'unique_together': {('date', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('refund', 'Refund'), ('fee', 'Service Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('sender_id', models.CharField(max_length=100)),
                ('receiver_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('receiver_name', models.CharField(blank=True, max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_description', models.TextField(blank=True)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('escrow_status', models.CharField(choices=[('holding', 'Holding'), ('released', 'Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='holding', max_length=20)),
                ('escrow_release_date', models.DateTimeField(blank=True, null=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('verification_expires', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
