# Generated by Django 5.2.4 on 2025-08-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
