# Generated by Django 5.2.4 on 2025-08-02 12:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_logo', models.URLField(blank=True, null=True)),
                ('loan_type', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('min_credit_score', models.IntegerField(default=300)),
                ('min_sales_history', models.IntegerField(default=0)),
                ('min_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('disbursement_time', models.CharField(default='5-7 days', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Loan Offer',
                'verbose_name_plural': 'Loan Offers',
                'ordering': ['interest_rate'],
            },
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('payment_reliability', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sales_history_months', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('customer_satisfaction', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Score',
                'verbose_name_plural': 'Credit Scores',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sales', models.IntegerField(default=0)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('top_category', models.CharField(blank=True, max_length=100)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-generated_at'],
                'unique_together': {('farmer', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('units_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_performance', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='marketplace.product')),
            ],
            options={
                'verbose_name': 'Product Performance',
                'verbose_name_plural': 'Product Performance',
                'ordering': ['-date'],
                'unique_together': {('farmer', 'product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sales', models.IntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenue_growth', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sales_growth', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('top_products', models.JSONField(blank=True, default=list)),
                ('monthly_trends', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Analytics',
                'verbose_name_plural': 'Sales Analytics',
                'ordering': ['-date'],
                'unique_together': {('farmer', 'date')},
            },
        ),
    ]
