# Generated by Django 5.2.4 on 2025-08-02 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('sales_data', 'Sales Data'), ('revenue_report', 'Revenue Report'), ('product_performance', 'Product Performance'), ('payment_analysis', 'Payment Analysis'), ('monthly_report', 'Monthly Report')], max_length=50)),
                ('date_range', models.CharField(choices=[('last_month', 'Last Month'), ('last_quarter', 'Last Quarter'), ('last_year', 'Last Year'), ('custom', 'Custom Range')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], default='csv', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('export_data', models.JSONField(blank=True, default=dict)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Request',
                'verbose_name_plural': 'Export Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('revenue', 'Revenue Target'), ('sales', 'Sales Count Target'), ('product', 'Product Sales Target'), ('growth', 'Growth Target')], max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('target_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Target',
                'verbose_name_plural': 'Sales Targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_period', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overdue_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('on_time_payments', models.IntegerField(default=0)),
                ('late_payments', models.IntegerField(default=0)),
                ('payment_reliability_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_trends', models.JSONField(blank=True, default=list)),
                ('customer_payment_behavior', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Analysis',
                'verbose_name_plural': 'Payment Analyses',
                'ordering': ['-generated_at'],
                'unique_together': {('farmer', 'analysis_period')},
            },
        ),
    ]
