# Generated by Django 5.2.4 on 2025-08-05 19:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_logisticsrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_request', 'New Logistics Request'), ('request_accepted', 'Request Accepted'), ('request_rejected', 'Request Rejected'), ('request_completed', 'Request Completed'), ('pickup_reminder', 'Pickup Reminder'), ('delivery_update', 'Delivery Update')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('logistics_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='logistics.logisticsrequest')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='logistics.serviceprovider')),
            ],
            options={
                'verbose_name': 'Logistics Notification',
                'verbose_name_plural': 'Logistics Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
