# Generated by Django 5.2.4 on 2025-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
