# Generated by Django 5.2.4 on 2025-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_options_alter_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
