# Generated by Django 5.2.4 on 2025-08-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_logisticsrequest'),
        ('orders', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='logistics.serviceprovider'),
        ),
    ]
