# Generated by Django 5.2.4 on 2025-08-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_notification_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_status', 'Order Status Update'), ('order_placed', 'Order Placed'), ('product_update', 'Product Update'), ('cart_added', 'Product Added to Cart'), ('system', 'System Notification')], max_length=20),
        ),
    ]
