# Generated by Django 5.2.4 on 2025-07-29 07:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('PDF Guide', 'PDF Guide'), ('Excel Tool', 'Excel Tool'), ('Video Guide', 'Video Guide'), ('Data Reports', 'Data Reports'), ('PDF Reference', 'PDF Reference')], max_length=50)),
                ('category', models.CharField(choices=[('health', 'Health'), ('tools', 'Tools'), ('planning', 'Planning'), ('soil', 'Soil'), ('market', 'Market'), ('certification', 'Certification')], max_length=100)),
                ('file_url', models.URLField()),
                ('file_size', models.CharField(max_length=20)),
                ('file_size_bytes', models.BigIntegerField()),
                ('downloads', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-downloads', '-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('farming', 'Farming'), ('planning', 'Planning'), ('technology', 'Technology'), ('climate', 'Climate'), ('livestock', 'Livestock'), ('soil', 'Soil'), ('pest-control', 'Pest Control'), ('harvesting', 'Harvesting'), ('soil_enrichment', 'Soil Enrichment')], max_length=100)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, choices=[('dry', 'Dry Season'), ('rainy', 'Rainy Season'), ('all', 'All Seasons')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('read_time', models.IntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_role', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True)),
                ('download_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('bookmarks', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Advisory Content',
                'ordering': ['-published_at', '-featured', '-views'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('farming', 'Farming'), ('planning', 'Planning'), ('technology', 'Technology'), ('climate', 'Climate'), ('livestock', 'Livestock'), ('soil', 'Soil'), ('pest-control', 'Pest Control')], max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('modules', models.JSONField(default=list)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True)),
                ('views', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-featured', '-views'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('bio', models.TextField()),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=50)),
                ('consultation_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('languages', models.JSONField(default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('profile_image', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('total_consultations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expert_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.expert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advisory_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.advisorycontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'advisory_content')},
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advisory_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.advisorycontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'advisory_content')},
            },
        ),
    ]
