# Generated by Django 5.2.4 on 2025-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='calendly_connected',
            field=models.BooleanField(default=False, help_text='Whether expert has connected their Calendly account'),
        ),
        migrations.AddField(
            model_name='expert',
            name='calendly_event_type_id',
            field=models.CharField(blank=True, help_text='Calendly event type ID for consultations', max_length=100),
        ),
        migrations.AddField(
            model_name='expert',
            name='calendly_link',
            field=models.URLField(blank=True, help_text='Calendly booking link for consultations'),
        ),
    ]
