# Generated by Django 5.2.4 on 2025-08-02 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_expert_calendly_connected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='ai_generation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resource',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='generated_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='generation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('tools', 'Tools'), ('planning', 'Planning'), ('soil', 'Soil'), ('market', 'Market'), ('certification', 'Certification'), ('ai_generated', 'AI Generated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('PDF Guide', 'PDF Guide'), ('Excel Tool', 'Excel Tool'), ('Video Guide', 'Video Guide'), ('Data Reports', 'Data Reports'), ('PDF Reference', 'PDF Reference'), ('AI Generated', 'AI Generated')], max_length=50),
        ),
    ]
