# Generated by Django 5.2.4 on 2025-08-02 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0003_resource_ai_generation_data_resource_ai_model_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_generation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='course',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='download_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='generated_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='generation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
